version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samCrudApi"
s3_bucket = "mys3bucketdata3"
s3_prefix = "samCrudApi"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
